# Utiliser les variables d'environnement, sinon utiliser les valeurs par défaut
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER:dev_user}
spring.datasource.password=${DB_PASSWORD:password123}
spring.datasource.driver-class-name=${DB_DRIVER}
spring.jpa.database-platform=${DB_DIALECT}
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:validate}

# Options d'affichage pratiques
spring.jpa.show-sql=${SHOW_SQL:false}
#spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true