spring.application.name=304

# URL de la base de données (h2db est le nom de la base, tu peux le changer)
spring.datasource.url=jdbc:h2:mem:h2db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Indique à Hibernate de créer automatiquement les tables en fonction de tes entités
spring.jpa.hibernate.ddl-auto=update
# Affiche les requêtes SQL dans la console de ton IDE (pratique pour le débug)
spring.jpa.show-sql=true

# Active l'interface web pour voir la base de données
spring.h2.console.enabled=true
# Le chemin pour accéder à l'interface web (http://localhost:8080/h2-console)
spring.h2.console.path=/h2-console